# 版权公司
owner_corp = "Everkm"

# 备案号
beian = ""

[[bottom_nav]]
title = "Home"
url = "https://www.everkm.cn"

[[bottom_nav]]
title = "Publish"
url = "https://publish.everkm.cn"

[[bottom_nav]]
title = "Note"
url = "https://note.everkm.cn"